sudo: required
before_install:
 - sudo add-apt-repository ppa:webupd8team/java -y
 - sudo apt-get -qq update
 - sudo apt-get install oracle-java8-installer -y
 - sudo apt-get install graphviz maven make devscripts debhelper rpm -y
 - export MAVEN_OPTS="-Xmx512m"

language: java

script: 
  - mvn clean install -DfullBuild -DskipTests
